# workflow name
name: Generate release-artifacts

# on events
on:
  release:
    types:
      - created

# workflow tasks
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: go-cross-build
        uses: thatisuday/go-cross-build@v1.1.0
        with:
            platforms: 'linux/amd64, darwin/amd64, windows/amd64, linux/mips, linux/mips64'
            package: ''
            name: 'go-godaddy-dyndns'
            compress: 'true'
            dest: 'dist'

  # copy build-artifacts in the GitHub release
      - name: Copy build-artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "./dist/*.tar.gz"
